spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    drive-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  jpa:
    show-sql: true # Opcional: mostra os SQLs gerados
    hibernate:
      #ddl-auto: none # 'update', 'create', 'validate', 'none'. 'update' ï¿½ comum em desenvolvimento
      dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect} # Dialeto para o Hibernate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true












